hop/musicstore/events/urls.py
from django.conf.urls import url
from . import views

app_name = "events_ns"

urlpatterns = [
    url(r'^$', views.show_events, name="show_events"),
]

hop/musicstore/payment/urls.py
from django.conf.urls import url
from . import views

app_name = "payment_ns"

urlpatterns = [
    url(r'^$', views.pay, name="pay"),
    url(r'^help/$', views.help, name="help"),
    url(r'^add_pmt/$', views.add_payment, name="add_pmt"),
    url(r'^edit_pmt/$', views.edit_payment, name="edit_pmt"),
    url(r'^delete_pmt/$', views.delete_payment, name= "delete_pmt")
]

hop/musicstore/song_mgt/urls.py
from django.conf.urls import url
from . import views

app_name = "song_mgt_ns"

urlpatterns = [
    url(r'^$', views.add_song, name="addsong"),
    url(r'^editsong/$', views.edit_song, name="editsong"),
    url(r'^deletesong/$', views.delete_song, name="deletesong"),
]

hop/musicstore/urls.py
from django.urls import include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib import admin
from musicstore.song_mgt import views as song_views

# For debugging purposes
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', song_views.fetch_all_songs),
    url(r'^payment/', include('musicstore.payment.urls',namespace="payment_ns")),
    url(r'^events/', include('musicstore.events.urls',namespace="events_ns")),
    url(r'^song_mgt/', include('musicstore.song_mgt.urls',namespace="song_mgt_ns")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

    

hop/musicstore/events/models.py
from django.db import models

# Create your models here.

hop/musicstore/payment/models.py
from django.db import models

# Create your models here.
class Payment(models.Model):
    card_number = models.BigIntegerField(unique=True)
    card_type = models.CharField(max_length=30)
    billing_address = models.CharField(max_length=1000)

    objects = models.Manager()

    class Meta: 
        ordering = ['-card_number']
        
def create_process(_card_number, _card_type, _billing_address):
    payment = Payment(card_number=_card_number, card_type=_card_type, billing_address=_billing_address)

    # Validation - Ensure the instance values comply with those of the model definition
    # Rasie ValidationError if the test failed
    payment.full_clean()
    
    # Create the record in the target database
    payment.save()

def fetch_all_pmt_methods_process():
    # Return a dict of payment methods
    return Payment.objects.in_bulk()
    
def fetch_payment_method_process(_id):
    return Payment.objects.get(id=_id)

def edit_process(_id, _card_number, _card_type, _billing_address):
    Payment.objects.filter(id=_id).update(card_number=_card_number, card_type=_card_type, billing_address=_billing_address)

def delete_process(_id):
    Payment.objects.filter(id=_id).delete()

hop/musicstore/song_mgt/models.py
from django.db import models

# Create your models here.


class Song(models.Model):
    title = models.CharField(max_length=30)
    artists = models.CharField(max_length=30)
    album = models.CharField(max_length=30)
    genre = models.CharField(max_length=30)
    year = models.IntegerField()
    album_image = models.URLField(max_length=1000)

    objects = models.Manager()

    class Meta:
        unique_together = ['title', 'artists']


def create_process(_title, _artists, _album, _genre, _year, _album_image):
    song = Song(title=_title, artists=_artists, album=_album,
                genre=_genre, year=_year, album_image=_album_image)

    # Validation - Ensure the instance values comply with those of the model definition
    # Rasie ValidationError if the test failed
    song.full_clean()
    
    # Create the record in the target database
    song.save()

def fetch_all_songs_process():
    # Return a dict of songs
    return Song.objects.in_bulk()

def fetch_song_process(_id):
    return Song.objects.get(id=_id)

def edit_process(_id, _title, _artists, _album, _genre, _year, _album_image):
    Song.objects.filter(id=_id).update(title=_title, artists=_artists, album=_album,
                genre=_genre, year=_year, album_image=_album_image)

def delete_process(_id):
    Song.objects.filter(id=_id).delete()

hop/musicstore/payment/forms.py
from django import forms
from datetime import date
import re

CARD_TYPES = ((0, 'American Express'), (1, 'Discover'),
              (2, 'Mastercard'), (3, 'Visa'))


class PaymentForm(forms.Form):
    card_number = forms.CharField()
    card_type = forms.ChoiceField(choices=CARD_TYPES)
    billing_address = forms.CharField()
    # Override the default field order, which is the declaration order
    field_order = ['card_type', 'card_number', 'billing_address']

    # This validator is invoked when is_valid() gets invoked
    def clean_card_number(self):
        error = False
        # Get the selected card type
        selected_card_type = CARD_TYPES[int(self.cleaned_data['card_type'])][1]
        # Get the field value from cleaned_data dict
        value = self.cleaned_data['card_number']
        # Check if the value is valid
        if(selected_card_type == 'American Express' and re.search(r"^3[47][0-9]{13}$", value) is None):
            error = True
        if(selected_card_type == 'Discover' and re.match(r"^6(?:011|5[0-9]{2})[0-9]{12}$", value) is None):
            error = True
        if(selected_card_type == 'Mastercard' and
           re.search(r"^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$", value) is None):
            error = True
        if(selected_card_type == 'Visa' and re.search(r"^4[0-9]{12}(?:[0-9]{3})?$", value) is None):
            error = True
        # Raise error
        if(error == True):
            raise forms.ValidationError(
                "Please enter a valid card number", code='cardnumber')
        # Always return value
        return value

class EditPaymentForm(forms.Form):
    id = forms.IntegerField(widget = forms.HiddenInput(), required = False)
    card_number = forms.CharField(widget = forms.HiddenInput(), required = False)
    card_type = forms.CharField(widget = forms.HiddenInput(), required = False)
    billing_address = forms.CharField()
    field_order = ['card_type', 'card_number', 'billing_address']

hop/musicstore/song_mgt/forms.py
from django import forms
from datetime import date

GENRES = ((0, 'Country Music'), (1, 'Dubstep'), (2, 'Electronic Dance Music'),
          (3, 'Indie Rock'), (4, 'Rap Music'), (5, 'Other'))


class SongForm(forms.Form):
    id = forms.IntegerField(widget = forms.HiddenInput(), required = False)
    title = forms.CharField()
    artists = forms.CharField()
    album = forms.CharField()
    genre = forms.ChoiceField(choices=GENRES)
    year = forms.IntegerField(min_value=1900,max_value=int(date.today().year))
    album_image = forms.URLField()
    # Override the default field order, which is the declaration order
    field_order = ['title', 'genre', 'artists','album','year','album_image']

def searchGenresForKey(value):
    for element in GENRES:
        if(value in element):
            return element[0]
    return -1

hop/musicstore/events/views.py
from django.shortcuts import render

# Create your views here.

def show_events(request):
    events = ["Anniversary 20th October", "Black Friday 29th November", "Christmas 23rd December"]
    return render(request, 'events/events.html', {"events": events})

hop/musicstore/payment/views.py
from django.shortcuts import render
from . import forms, models
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
import sys

# Create your views here.

def pay(request):
    pmt_method_dict = models.fetch_all_pmt_methods_process()

    return render(request,'payment/pay.html', {'pmt_method_dict': pmt_method_dict})

def help(request):
    contact_name = 'Dustin'
    contact_address = {'sector':'#385','city':'Sabody','planet':'Moon'}
    contact_phone = ['123-456-789','987-654-321']
    contact_hours = ((0,'Mon-Thu 7AM-12PM'),(1,'Fri 1PM-5PM'),(2,'Sat-Sun 7AM-10AM'))
    # Package up all variables into a dictionary
    contact_info = {'contact_name':contact_name, 'contact_address':contact_address, 'contact_phone':contact_phone, 'contact_hours':contact_hours}
    return render(request,'payment/help.html', contact_info)

def add_payment(request):
    title = 'Add a new payment method'
    if request.method == 'POST':
        # POST, generate form with data from the request
        form = forms.PaymentForm(request.POST)
        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            card_number = form.cleaned_data['card_number']
            card_type = forms.CARD_TYPES[int(form.cleaned_data['card_type'])][1]
            billing_address = form.cleaned_data['billing_address']
            
            try:
                models.create_process(card_number, card_type, billing_address)
                action = 'POST_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'POST_FAILED'
            except:
                print("Unexpected error: " + str(sys.exc_info()[0]))
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'POST_FAILED'
        else:
            action='POST_FAILED'
    else:
        action='GET'
        # Disable auto_id to prevent the form from generating verbose information.
        # Also, we set the initial value to the album image field
        form = forms.PaymentForm(auto_id=False)
    # Reference form instance (bound/unbound) is sent to template for rendering
    return render(request,'payment/payment_form.html',{'action':action,'form':form,'title':title})

def edit_payment(request):
    id = request.POST.get('id','')
    context = {'card_number': '', 'card_type': ''}

    # If id doesn't exist, redirect to the homepage
    if(id == ''):
        return HttpResponseRedirect('/payment/#mainsection')
    
    title = "Edit payment method"
    # Create an empty form so that Django doesn't complaint
    form = forms.EditPaymentForm()

    if('popup' in id):
        action = ''

        # Clean up the id
        id = id.replace('popup','')

        try:
            # Fetch the payment method from the DB based on the given id, and then populate the fields 
            payment_method = models.fetch_payment_method_process(id)
            form = forms.EditPaymentForm(auto_id=False, initial={'id':payment_method.id,'card_number':payment_method.card_number,
            'card_type':payment_method.card_type,
            'billing_address':payment_method.billing_address})

            # Update context
            context['card_number'] = '****-****-****-' + str(payment_method.card_number)[12:]
            context['card_type'] = payment_method.card_type

        except ValidationError as err:
            for err in err.messages:
                form.add_error(None, err)
            action = 'ERROR'
        except:
            print('Unexpected error: ' + str(sys.exc_info()[0]))
            action = 'ERROR'
    else:

        form = forms.EditPaymentForm(request.POST)

        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            # Extract form values
            card_number = form.cleaned_data['card_number']
            card_type = form.cleaned_data['card_type']
            billing_address = form.cleaned_data['billing_address']

            # Update context
            context['card_number'] = '****-****-****-' + str(card_number)[12:]
            context['card_type'] = card_type
            
            try:
                models.edit_process(id, int(card_number), card_type, billing_address)
                action = 'EDIT_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'ERROR'
            except:
                print("Unexpected error: " + sys.exc_info()[0])
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'ERROR'
        else:
            action = 'ERROR'

    return render(request, 'payment/edit_payment_form.html', {'action': action, 'context':context, 'form': form, 'title': title})

def delete_payment(request):

    id = request.POST.get('id', '')
    if(id == ''):
        return HttpResponseRedirect('/payment/#mainsection')
    else:
        id = id.replace('popup','')

    try:
        models.delete_process(id)
    except:
        print("Unexpected error: " + sys.exc_info()[0])

    return HttpResponseRedirect('/payment/#mainsection')

hop/musicstore/song_mgt/views.py
from django.shortcuts import render
from . import forms, models
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
import sys 

# Create your views here.


def add_song(request):
    title = "Add a new song"
    if request.method == 'POST':
        # POST, generate form with data from the request
        form = forms.SongForm(request.POST)
        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            # Extract form values
            song_title = form.cleaned_data['title']
            artists = form.cleaned_data['artists']
            album = form.cleaned_data['album']
            genre = forms.GENRES[int(form.cleaned_data['genre'])][1]
            year = form.cleaned_data['year']
            album_image = form.cleaned_data['album_image']

            try:
                models.create_process(song_title, artists, album, genre, year, album_image)
                action = 'POST_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'POST_FAILED'
            except:
                print("Unexpected error: " + sys.exc_info()[0])
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'POST_FAILED'
        else:
            action = 'POST_FAILED'
    else:
        action = 'GET'
        form = forms.SongForm(auto_id=False, initial={
                              'album_image': 'http://'})
    return render(request, 'song/song_form.html', {'action': action, 'form': form, 'title': title})

def fetch_all_songs(request):
    song_dict = models.fetch_all_songs_process()
    
    return render(request, 'homepage.html', {'song_dict': song_dict})

def edit_song(request):
    id = request.POST.get('id','')

    # If id doesn't exist, redirect to the homepage
    if(id == ''):
        return HttpResponseRedirect('/')
    
    title = "Edit song"
    # Create an empty form so that Django doesn't complaint
    form = forms.SongForm()

    if('popup' in id):
        action = ''

        # Clean up the id
        id = id.replace('popup','')

        try:
            # Fetch the song from the DB based on the given id, and then populate the fields 
            song = models.fetch_song_process(id)
            form = forms.SongForm(auto_id=False, initial={'id':song.id,'title':song.title,
            'artists':song.artists,'album':song.album,'genre':forms.searchGenresForKey(song.genre),
            'year':song.year,'album_image': song.album_image})
        except ValidationError as err:
            for err in err.messages:
                form.add_error(None, err)
            action = 'ERROR'
        except:
            print('Unexpected error: ' + str(sys.exc_info()[0]))
            action = 'ERROR'
    else:
        form = forms.SongForm(request.POST)
        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            # Extract form values
            song_title = form.cleaned_data['title']
            artists = form.cleaned_data['artists']
            album = form.cleaned_data['album']
            genre = forms.GENRES[int(form.cleaned_data['genre'])][1]
            year = form.cleaned_data['year']
            album_image = form.cleaned_data['album_image']

            try:
                models.edit_process(id, song_title, artists, album, genre, year, album_image)
                action = 'EDIT_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'ERROR'
            except:
                print("Unexpected error: " + sys.exc_info()[0])
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'ERROR'
        else:
            action = 'ERROR'

    return render(request, 'song/edit_song_form.html', {'action': action, 'form': form, 'title': title})

def delete_song(request):

    id = request.POST.get('id','')
    if(id == ''):
        return HttpResponseRedirect('/')
    else:
        id = id.replace('popup','')

    try:
        models.delete_process(id)
    except:
        print("Unexpected error: " + sys.exc_info()[0])

    return HttpResponseRedirect('/')

hop/musicstore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Music Store</title>

    <!-- Custom fonts for this theme -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
        type="text/css">
    <script src="https://kit.fontawesome.com/6b4d8e3e91.js" crossorigin="anonymous"></script>

    <!-- Theme CSS -->
    <link href="{% static 'css/freelancer.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/">Music Store</a>
            <button
                class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
                type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                            href="{% url 'song_mgt_ns:addsong' %}#mainsection">Add Song</a>
                    </li>
                    <li class="nav-item dropdown mx-0 mx-lg-1" style="padding-top:0.5rem">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Payment
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'payment_ns:pay' %}#mainsection">Payment
                                methods</a>
                            <a class="dropdown-item" href="{% url 'payment_ns:add_pmt' %}#mainsection">Add payment
                                method</a>
                            <a class="dropdown-item" href="{% url 'payment_ns:help' %}#mainsection">Payment
                                Assistance</a>
                        </div>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                            href="{% url 'events_ns:show_events' %}#mainsection">Special Events</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">

            <!-- Masthead Heading -->
            <h1 class="masthead-heading text-uppercase mb-0">Music Store</h1>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Masthead Subheading -->
            <p class="masthead-subheading font-weight-light mb-0">CS 260 - Django Web Development</p>

        </div>
    </header>

    <!-- Main Section -->
    <section class="page-section" id="mainsection">

        <!-- Main Section Heading -->
        {% block header %}{% endblock header %}

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Main Block -->
        {% block main %}{% endblock %}
    </section>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; CityU 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>

</body>

</html>

hop/musicstore/templates/divider.html
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="{{icon_class}}">
        <i class="{{icon}}"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

hop/musicstore/templates/homepage.html
{% extends "base.html" %}

{% block header %}
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Homepage</h2>
{% endblock header %}

{% block main%}
<div class="container">
    <!-- Main Content -->
    {% if song_dict %}
        <div class="row">

        <!-- Show song thumbnails -->
        {% for song in song_dict.values %}

            {% include "song/song_thumbnail.html" with id=song.id title=song.title artists=song.artists album_image=song.album_image %} 
            {% include "song/song_popup.html" with id=song.id title=song.title artists=song.artists album=song.album genre=song.genre year=song.year album_image=song.album_image %}

        {% endfor %}

        </div>
    {% endif %}

    {% include "divider.html" with icon_class="divider-custom-icon" icon="fas fa-star" %}
    <div style="text-align: center;">
        <p><b>Hotline:</b> {{ HOTLINE.name }} - {{ HOTLINE.phone }}</p>
    </div>

</div>
{% endblock %}