hop/musicstore/events/urls.py
from django.conf.urls import url
from . import views

app_name = "events_ns"

urlpatterns = [
    url(r'^$', views.show_events, name="show_events"),
]

hop/musicstore/payment/urls.py
from django.conf.urls import url
from . import views

app_name = "payment_ns"

urlpatterns = [
    url(r'^$', views.pay, name="pay"),
    url(r'^help/$', views.help, name="help"),
    url(r'^add_pmt/$', views.add_payment, name="add_pmt"),
    url(r'^edit_pmt/$', views.edit_payment, name="edit_pmt"),
    url(r'^delete_pmt/$', views.delete_payment, name= "delete_pmt")
]

hop/musicstore/song_mgt/urls.py
from django.conf.urls import url
from . import views

app_name = "song_mgt_ns"

urlpatterns = [
    url(r'^$', views.add_song, name="addsong"),
    url(r'^editsong/$', views.edit_song, name="editsong"),
    url(r'^deletesong/$', views.delete_song, name="deletesong"),
]

hop/musicstore/urls.py
from django.urls import include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib import admin
from musicstore.song_mgt import views as song_views

# For debugging purposes
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', song_views.fetch_all_songs),
    url(r'^payment/', include('musicstore.payment.urls',namespace="payment_ns")),
    url(r'^events/', include('musicstore.events.urls',namespace="events_ns")),
    url(r'^song_mgt/', include('musicstore.song_mgt.urls',namespace="song_mgt_ns")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

    

hop/musicstore/events/models.py
from django.db import models

# Create your models here.

hop/musicstore/payment/models.py
from django.db import models

# Create your models here.
class Payment(models.Model):
    card_number = models.BigIntegerField(unique=True)
    card_type = models.CharField(max_length=30)
    billing_address = models.CharField(max_length=1000)

    objects = models.Manager()

    class Meta: 
        ordering = ['-card_number']
        
def create_process(_card_number, _card_type, _billing_address):
    payment = Payment(card_number=_card_number, card_type=_card_type, billing_address=_billing_address)

    # Validation - Ensure the instance values comply with those of the model definition
    # Rasie ValidationError if the test failed
    payment.full_clean()
    
    # Create the record in the target database
    payment.save()

def fetch_all_pmt_methods_process():
    # Return a dict of payment methods
    return Payment.objects.in_bulk()
    
def fetch_payment_method_process(_id):
    return Payment.objects.get(id=_id)

def edit_process(_id, _card_number, _card_type, _billing_address):
    Payment.objects.filter(id=_id).update(card_number=_card_number, card_type=_card_type, billing_address=_billing_address)

def delete_process(_id):
    Payment.objects.filter(id=_id).delete()

hop/musicstore/song_mgt/models.py
from django.db import models

# Create your models here.


class Song(models.Model):
    title = models.CharField(max_length=30)
    artists = models.CharField(max_length=30)
    album = models.CharField(max_length=30)
    genre = models.CharField(max_length=30)
    year = models.IntegerField()
    album_image = models.URLField(max_length=1000)

    objects = models.Manager()

    class Meta:
        unique_together = ['title', 'artists']


def create_process(_title, _artists, _album, _genre, _year, _album_image):
    song = Song(title=_title, artists=_artists, album=_album,
                genre=_genre, year=_year, album_image=_album_image)

    # Validation - Ensure the instance values comply with those of the model definition
    # Rasie ValidationError if the test failed
    song.full_clean()
    
    # Create the record in the target database
    song.save()

def fetch_all_songs_process():
    # Return a dict of songs
    return Song.objects.in_bulk()

def fetch_song_process(_id):
    return Song.objects.get(id=_id)

def edit_process(_id, _title, _artists, _album, _genre, _year, _album_image):
    Song.objects.filter(id=_id).update(title=_title, artists=_artists, album=_album,
                genre=_genre, year=_year, album_image=_album_image)

def delete_process(_id):
    Song.objects.filter(id=_id).delete()

hop/musicstore/payment/forms.py
from django import forms
from datetime import date
import re

CARD_TYPES = ((0, 'American Express'), (1, 'Discover'),
              (2, 'Mastercard'), (3, 'Visa'))


class PaymentForm(forms.Form):
    card_number = forms.CharField()
    card_type = forms.ChoiceField(choices=CARD_TYPES)
    billing_address = forms.CharField()
    # Override the default field order, which is the declaration order
    field_order = ['card_type', 'card_number', 'billing_address']

    # This validator is invoked when is_valid() gets invoked
    def clean_card_number(self):
        error = False
        # Get the selected card type
        selected_card_type = CARD_TYPES[int(self.cleaned_data['card_type'])][1]
        # Get the field value from cleaned_data dict
        value = self.cleaned_data['card_number']
        # Check if the value is valid
        if(selected_card_type == 'American Express' and re.search(r"^3[47][0-9]{13}$", value) is None):
            error = True
        if(selected_card_type == 'Discover' and re.match(r"^6(?:011|5[0-9]{2})[0-9]{12}$", value) is None):
            error = True
        if(selected_card_type == 'Mastercard' and
           re.search(r"^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$", value) is None):
            error = True
        if(selected_card_type == 'Visa' and re.search(r"^4[0-9]{12}(?:[0-9]{3})?$", value) is None):
            error = True
        # Raise error
        if(error == True):
            raise forms.ValidationError(
                "Please enter a valid card number", code='cardnumber')
        # Always return value
        return value

class EditPaymentForm(forms.Form):
    id = forms.IntegerField(widget = forms.HiddenInput(), required = False)
    card_number = forms.CharField(widget = forms.HiddenInput(), required = False)
    card_type = forms.CharField(widget = forms.HiddenInput(), required = False)
    billing_address = forms.CharField()
    field_order = ['card_type', 'card_number', 'billing_address']

hop/musicstore/song_mgt/forms.py
from django import forms
from datetime import date

GENRES = ((0, 'Country Music'), (1, 'Dubstep'), (2, 'Electronic Dance Music'),
          (3, 'Indie Rock'), (4, 'Rap Music'), (5, 'Other'))


class SongForm(forms.Form):
    id = forms.IntegerField(widget = forms.HiddenInput(), required = False)
    title = forms.CharField()
    artists = forms.CharField()
    album = forms.CharField()
    genre = forms.ChoiceField(choices=GENRES)
    year = forms.IntegerField(min_value=1900,max_value=int(date.today().year))
    album_image = forms.URLField()
    # Override the default field order, which is the declaration order
    field_order = ['title', 'genre', 'artists','album','year','album_image']

def searchGenresForKey(value):
    for element in GENRES:
        if(value in element):
            return element[0]
    return -1

hop/musicstore/events/views.py
from django.shortcuts import render

# Create your views here.

def show_events(request):
    events = ["Anniversary 20th October", "Black Friday 29th November", "Christmas 23rd December"]
    return render(request, 'events/events.html', {"events": events})

hop/musicstore/payment/views.py
from django.shortcuts import render
from . import forms, models
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
import sys

# Create your views here.

def pay(request):
    pmt_method_dict = models.fetch_all_pmt_methods_process()

    return render(request,'payment/pay.html', {'pmt_method_dict': pmt_method_dict})

def help(request):
    contact_name = 'Dustin'
    contact_address = {'sector':'#385','city':'Sabody','planet':'Moon'}
    contact_phone = ['123-456-789','987-654-321']
    contact_hours = ((0,'Mon-Thu 7AM-12PM'),(1,'Fri 1PM-5PM'),(2,'Sat-Sun 7AM-10AM'))
    # Package up all variables into a dictionary
    contact_info = {'contact_name':contact_name, 'contact_address':contact_address, 'contact_phone':contact_phone, 'contact_hours':contact_hours}
    return render(request,'payment/help.html', contact_info)

def add_payment(request):
    title = 'Add a new payment method'
    if request.method == 'POST':
        # POST, generate form with data from the request
        form = forms.PaymentForm(request.POST)
        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            card_number = form.cleaned_data['card_number']
            card_type = forms.CARD_TYPES[int(form.cleaned_data['card_type'])][1]
            billing_address = form.cleaned_data['billing_address']
            
            try:
                models.create_process(card_number, card_type, billing_address)
                action = 'POST_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'POST_FAILED'
            except:
                print("Unexpected error: " + str(sys.exc_info()[0]))
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'POST_FAILED'
        else:
            action='POST_FAILED'
    else:
        action='GET'
        # Disable auto_id to prevent the form from generating verbose information.
        # Also, we set the initial value to the album image field
        form = forms.PaymentForm(auto_id=False)
    # Reference form instance (bound/unbound) is sent to template for rendering
    return render(request,'payment/payment_form.html',{'action':action,'form':form,'title':title})

def edit_payment(request):
    id = request.POST.get('id','')
    context = {'card_number': '', 'card_type': ''}

    # If id doesn't exist, redirect to the homepage
    if(id == ''):
        return HttpResponseRedirect('/payment/#mainsection')
    
    title = "Edit payment method"
    # Create an empty form so that Django doesn't complaint
    form = forms.EditPaymentForm()

    if('popup' in id):
        action = ''

        # Clean up the id
        id = id.replace('popup','')

        try:
            # Fetch the payment method from the DB based on the given id, and then populate the fields 
            payment_method = models.fetch_payment_method_process(id)
            form = forms.EditPaymentForm(auto_id=False, initial={'id':payment_method.id,'card_number':payment_method.card_number,
            'card_type':payment_method.card_type,
            'billing_address':payment_method.billing_address})

            # Update context
            context['card_number'] = '****-****-****-' + str(payment_method.card_number)[12:]
            context['card_type'] = payment_method.card_type

        except ValidationError as err:
            for err in err.messages:
                form.add_error(None, err)
            action = 'ERROR'
        except:
            print('Unexpected error: ' + str(sys.exc_info()[0]))
            action = 'ERROR'
    else:

        form = forms.EditPaymentForm(request.POST)

        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            # Extract form values
            card_number = form.cleaned_data['card_number']
            card_type = form.cleaned_data['card_type']
            billing_address = form.cleaned_data['billing_address']

            # Update context
            context['card_number'] = '****-****-****-' + str(card_number)[12:]
            context['card_type'] = card_type
            
            try:
                models.edit_process(id, int(card_number), card_type, billing_address)
                action = 'EDIT_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'ERROR'
            except:
                print("Unexpected error: " + sys.exc_info()[0])
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'ERROR'
        else:
            action = 'ERROR'

    return render(request, 'payment/edit_payment_form.html', {'action': action, 'context':context, 'form': form, 'title': title})

def delete_payment(request):

    id = request.POST.get('id', '')
    if(id == ''):
        return HttpResponseRedirect('/payment/#mainsection')
    else:
        id = id.replace('popup','')

    try:
        models.delete_process(id)
    except:
        print("Unexpected error: " + sys.exc_info()[0])

    return HttpResponseRedirect('/payment/#mainsection')

hop/musicstore/song_mgt/views.py
from django.shortcuts import render
from . import forms, models
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
import sys 

# Create your views here.


def add_song(request):
    title = "Add a new song"
    if request.method == 'POST':
        # POST, generate form with data from the request
        form = forms.SongForm(request.POST)
        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            # Extract form values
            song_title = form.cleaned_data['title']
            artists = form.cleaned_data['artists']
            album = form.cleaned_data['album']
            genre = forms.GENRES[int(form.cleaned_data['genre'])][1]
            year = form.cleaned_data['year']
            album_image = form.cleaned_data['album_image']

            try:
                models.create_process(song_title, artists, album, genre, year, album_image)
                action = 'POST_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'POST_FAILED'
            except:
                print("Unexpected error: " + sys.exc_info()[0])
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'POST_FAILED'
        else:
            action = 'POST_FAILED'
    else:
        action = 'GET'
        form = forms.SongForm(auto_id=False, initial={
                              'album_image': 'http://'})
    return render(request, 'song/song_form.html', {'action': action, 'form': form, 'title': title})

def fetch_all_songs(request):
    song_dict = models.fetch_all_songs_process()
    
    return render(request, 'homepage.html', {'song_dict': song_dict})

def edit_song(request):
    id = request.POST.get('id','')

    # If id doesn't exist, redirect to the homepage
    if(id == ''):
        return HttpResponseRedirect('/')
    
    title = "Edit song"
    # Create an empty form so that Django doesn't complaint
    form = forms.SongForm()

    if('popup' in id):
        action = ''

        # Clean up the id
        id = id.replace('popup','')

        try:
            # Fetch the song from the DB based on the given id, and then populate the fields 
            song = models.fetch_song_process(id)
            form = forms.SongForm(auto_id=False, initial={'id':song.id,'title':song.title,
            'artists':song.artists,'album':song.album,'genre':forms.searchGenresForKey(song.genre),
            'year':song.year,'album_image': song.album_image})
        except ValidationError as err:
            for err in err.messages:
                form.add_error(None, err)
            action = 'ERROR'
        except:
            print('Unexpected error: ' + str(sys.exc_info()[0]))
            action = 'ERROR'
    else:
        form = forms.SongForm(request.POST)
        # Call is_valid() to validate data and create cleaned_data and errors dict
        if form.is_valid():
            # Extract form values
            song_title = form.cleaned_data['title']
            artists = form.cleaned_data['artists']
            album = form.cleaned_data['album']
            genre = forms.GENRES[int(form.cleaned_data['genre'])][1]
            year = form.cleaned_data['year']
            album_image = form.cleaned_data['album_image']

            try:
                models.edit_process(id, song_title, artists, album, genre, year, album_image)
                action = 'EDIT_SUCCESSFULL'
            except ValidationError as err:
                for err in err.messages:
                    form.add_error(None, err)
                action = 'ERROR'
            except:
                print("Unexpected error: " + sys.exc_info()[0])
                form.add_error(None,'Unexpected error - Please contact your system administrator')
                action = 'ERROR'
        else:
            action = 'ERROR'

    return render(request, 'song/edit_song_form.html', {'action': action, 'form': form, 'title': title})

def delete_song(request):

    id = request.POST.get('id','')
    if(id == ''):
        return HttpResponseRedirect('/')
    else:
        id = id.replace('popup','')

    try:
        models.delete_process(id)
    except:
        print("Unexpected error: " + sys.exc_info()[0])

    return HttpResponseRedirect('/')

hop/musicstore/templates/payment/edit_payment_form.html
{% extends "base.html" %}
{% block header %}
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">{{ title }}</h2>
{% endblock header %}

{% block main%}

<!-- Main Content -->
<h4 class="text-center text-uppercase text-secondary mb-0" style="padding-bottom: 1rem;">{{ context.card_type }} : {{ context.card_number }}</h4>

{% if action == 'EDIT_SUCCESSFULL' %}
<div class="alert alert-success" role="alert">
    The payment method has been updated. <a href="/payment/#mainsection" class="alert-link">Go to payment page</a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif action == 'ERROR' %}
<div class="alert alert-danger" role="alert">
    Failed to edit the payment method! Please check the error messages.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<form method="POST">
    {% csrf_token %}

    <table
        style="margin-left:auto; margin-right:auto; margin-bottom:50px; border-collapse: separate;border-spacing: 50px 0;">
        <tr>
            <td colspan="3">
                {% if form.non_field_errors %}
                <div class="row">
                    <ul>
                        {% for error in form.non_field_errors %}
                        <li><div style="color: #FF5733; padding-left: 0.5rem;">{{error}}</div></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </td>
        </tr>
        {% for field in form.visible_fields %}
        <tr>
            <td>
                {{ field.label_tag }}
                {% if field.help_text %}
                <sup>{{ field.help_text }}</sup>
                {% endif %}
            </td>
            <td>
                <span class="float-left">{{ field }}</span>
                <span class="float-left">
                    {% for error in field.errors %}
                    <div style="color: #FF5733; padding-left: 0.5rem;">{{error}}</div>
                    {% endfor %}
                </span>
            </td>
        </tr>
        {% endfor %}
        {% for field in form.hidden_fields %}
            <div style="display:none;">{{ field }}</div>
        {% endfor %}
    </table>
    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock%}

hop/musicstore/templates/payment/help.html
{% extends "base.html" %}

{% block header %}
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Payment Assistance</h2>
{% endblock header %}

{% block main%}

<!-- Main Content -->
<div style="text-align: center;">
    <h4>Name: {{contact_name}}</h4>
    <p>Address: {{contact_address.sector}} {{contact_address.city}},{{contact_address.planet}}</p>
    <p>Phone numbers: {{contact_phone.0}} and {{contact_phone.1}}</p>
    <p>Working Hours: {{contact_hours.0.1}}, {{contact_hours.1.1}}, and {{contact_hours.2.1}}</p>
</div>

{% endblock%}

hop/musicstore/templates/payment/pay.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Payment</h2>
{% endblock header %}

{% block main%}

<!-- Main Content -->
<div class="container">
    <!-- Main Content -->
    {% if pmt_method_dict %}
        <div class="row">

        <!-- Show song thumbnails -->
        {% for payment in pmt_method_dict.values %}

            {% include "payment/pmt_thumbnail.html" with id=payment.id card_number=payment.card_number card_type=payment.card_type %} 
            {% include "payment/pmt_popup.html" with id=payment.id card_number=payment.card_number card_type=payment.card_type billing_address=payment.billing_address %}

        {% endfor %}

        </div>
    {% endif %}
</div>
<div style="text-align: center;">
    <img src="{% static 'apps/payment/payment.png' %}" class="rounded" alt="payment">
</div>

{% endblock%}

hop/musicstore/templates/payment/payment_form.html
{% extends "base.html" %}
{% block header %}
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">{{ title }}</h2>
{% endblock header %}

{% block main%}

<!-- Main Content -->

{% if action == 'POST_SUCCESSFULL' %}
<div class="alert alert-success" role="alert">
    The payment method has been added. <a href="/payment/#mainsection" class="alert-link">Go to payment page</a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif action == 'POST_FAILED' %}
<div class="alert alert-danger" role="alert">
    Failed to add payment method! Please check the error messages.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<form method="POST">
    {% csrf_token %}

    <table
        style="margin-left:auto; margin-right:auto; margin-bottom:50px; border-collapse: separate;border-spacing: 50px 0;">
        <tr>
            <td colspan="3">
                {% if form.non_field_errors %}
                <div class="row">
                    <ul>
                        {% for error in form.non_field_errors %}
                        <li><div style="color: #FF5733; padding-left: 0.5rem;">{{error}}</div></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </td>
        </tr>
        {% for field in form %}
        <tr>
            <td>
                {{ field.label_tag }}
                {% if field.help_text %}
                <sup>{{ field.help_text }}</sup>
                {% endif %}
            </td>
            <td>
                <span class="float-left">{{ field }}</span>
                <span class="float-left">
                    {% for error in field.errors %}
                    <div style="color: #FF5733; padding-left: 0.5rem;">{{error}}</div>
                    {% endfor %}
                </span>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock%}

hop/musicstore/templates/payment/pmt_popup.html
{% load static %}
{% static "" as baseUrl %}
<div class="portfolio-modal modal fade" id="pmtid{{id}}" tabindex="-1" role="dialog" aria-labelledby="pmtid{{id}}Label"
    aria-hidden="true">
    <div class="modal-dialog" style="max-width: 800px;" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">
                    <i class="fas fa-times"></i>
                </span>
            </button>
            <div class="modal-body text-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <!-- Title -->
                            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">****-****-****-{{card_number|make_list|slice:'12:'|join:''}}</h2>
                            <!-- Icon Divider -->
                            <div class="divider-custom">
                                <div class="divider-custom-line"></div>
                                <div class="divider-custom-icon">
                                    <i class="fas fa-star"></i>
                                </div>
                                <div class="divider-custom-line"></div>
                            </div>
                            <!-- Image -->
                            <img class="img-fluid rounded mb-5" style="width: 300px;height: 300px;" src="{{baseUrl}}apps/payment/{{card_type}}.svg" alt="">
                            <!-- Text -->
                            <table
                                style="margin-left:auto; margin-right:auto; margin-bottom:50px; border-collapse: separate;border-spacing: 50px 0;">
                                <tr>
                                    <td class="font-weight-bold">Billing address:</td>
                                    <td>{{billing_address}}</td>
                                </tr>
                            </table>
                            <form method="post" action="{% url 'payment_ns:edit_pmt' %}#mainsection" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" name="id" value="{{id}}popup" class="btn btn-warning active">
                                    <i class="fa fa-pencil fa-fw"></i>
                                    Edit
                                </button>
                            </form>
                            <form method="post" action="{% url 'payment_ns:delete_pmt' %}#mainsection" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" name="id" value="{{id}}popup" class="btn btn-danger active">
                                    <i class="fa fa-trash fa-fw"></i>
                                    Delete
                                </button>
                            </form>
                            <button class="btn btn-primary" href="#" data-dismiss="modal">
                                <i class="fas fa-times fa-fw"></i>
                                Close Window
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

hop/musicstore/templates/payment/pmt_thumbnail.html
{% load static %}
{% static "" as baseUrl %}
<div class="col-md-6 col-lg-4">
    <div class="portfolio-item mx-auto text-center" data-toggle="modal" data-target="#pmtid{{id}}">
        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
            <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-music fa-3x"></i>
            </div>
        </div>
        <img class="img-fluid" style="width: 200px;height: 150px;" src="{{baseUrl}}apps/payment/{{card_type}}.svg" alt="">
        <p class="py-3 font-weight-bold">****-****-****-{{card_number|make_list|slice:'12:'|join:''}}</p>
    </div>
</div>